### PR TITLE
Handling when raw_data is None

### PR DESCRIPTION
**Pull request by girishkumarkh**
This happens on some occasions when geolocate IP couldn't find the IP's location

Error log:
```
backend_1      |  [2021-03-24 11:20:45,391] root         ERROR    Couldn't geolocate ip (middleware 1 140405557767496)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 26, in process_request
backend_1      |     self._get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 61, in _get_geolocation
backend_1      |     self._geolocation_data = get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/utils.py", line 52, in get_geolocation
backend_1      |     return backend_instance.data()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/base.py", line 33, in data
backend_1      |     self._parse()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/ipdataco.py", line 26, in _parse
backend_1      |     self._continent = self._raw_data.get('continent_name')
backend_1      | AttributeError: 'NoneType' object has no attribute 'get'
backend_1      | [2021-03-24 11:20:45,533] root         ERROR    Couldn't geolocate ip (middleware 1 140405557767496)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 42, in process_response
backend_1      |     self._get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/middleware.py", line 61, in _get_geolocation
backend_1      |     self._geolocation_data = get_geolocation(request)
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/utils.py", line 52, in get_geolocation
backend_1      |     return backend_instance.data()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/base.py", line 33, in data
backend_1      |     self._parse()
backend_1      |   File "/usr/local/lib/python3.8/site-packages/django_ip_geolocation/backends/ipdataco.py", line 26, in _parse
backend_1      |     self._continent = self._raw_data.get('continent_name')
backend_1      | AttributeError: 'NoneType' object has no attribute 'get'
```

### CODE REVIEW

**Comment by girishkumarkh** [comment]
@rednaks Seems like `travis-ci` has some issues but tests are passing as far as I can see. 

maybe this project can use github actions?

**Comment by rednaks** [comment]
Thank you @girishkumarkh  for the PR, I'll check why travis is failing. I'll probably drop `python-2.7` tests too since it's deprecated.

Regarding the PR instead of adding an `if self._raw_data:`  in ef90ad0d465990bc39ed1a122e13f92c1dfdffee706e478bf0ee6a7082dafa9bR26 
I'd prefer to initialize `self._raw_data` to an empty dict  in https://github.com/rednaks/django-ip-geolocation/blob/master/django_ip_geolocation/backends/base.py#L17

`self._raw_data = {}` instead of `self._raw_data = None`

**Comment by girishkumarkh** [comment]
amazing that would be a much elegant solution -- updated my PR now

**Comment by girishkumarkh** [comment]
@rednaks dropped 2.7 support and made some modification to the `.travis.yml` file and `tox.ini` file. Travis CI is now passing with this.

**Comment by rednaks** [comment]
thank you, looks good to me :)

**Comment by girishkumarkh** [comment]
Fantastic! thanks for merging it. Let me know if we can do a minor release.

**Comment by rednaks** [comment]
You're welcome, thank you for the contribution :)  
I published the release on pypi you may update your packages ! 

https://pypi.org/project/django-ip-geolocation/1.6.1/

**Pull request merged**
